sources:
  - RadioCanada.glyphs
  - RadioCanada-Italic.glyphs
axisOrder:
  - wght
  - wdth
  - ital
familyName: Radio-Canada
stat:
  RadioCanada[wdth,wght].ttf:
  - name: Width
    tag: wdth
    values:
    - name: Condensed
      value: 75
    - name: Medium
      value: 100
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
  RadioCanada-Italic[wdth,wght].ttf:
  - name: Width
    tag: wdth
    values:
    - name: Condensed
      value: 75
    - name: Medium
      value: 100
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1
